export const Grocery = [
  {
    id: 1,
    Name: "Rice",
    Category: "Grocery & Kitchen",
    Quantity: "1 KG",
    Price: 56,
    Picture: require("../assets/svg/rice.png"),
  },
  {
    id: 2,
    Name: "Fortune Oil",
    category: "Grocery & Kitchen",
    Quantity: "1L",
    Price: 125,
    Picture: require("../assets/svg/fortuneOil.png"),
  },
  {
    id: 3,
    Name: "Minappapu",
    category: "Grocery & Kitchen",
    Quantity: "1Kg",
    Price: 125,
    Picture: require("../assets/svg/minappapu.png"),
  },
  {
    id: 4,
    Name: "Swastik Mirchi",
    category: "Grocery & Kitchen",
    Quantity: "1Kg",
    Price: 125,
    Picture: require("../assets/svg/swastikMirchi.jpg"),
  },
  {
    id: 5,
    Name: "Annapurna Salt",
    category: "Grocery & Kitchen",
    Quantity: "1Kg",
    Price: 38,
    Picture: require("../assets/svg/annapurnaSalt.jpg"),
  },
  {
    id: 6,
    Name: "Boost",
    category: "Grocery & Kitchen",
    Quantity: "1Kg",
    Price: 240,
    Picture: require("../assets/svg/boost.jpg"),
  },
  {
    id: 7,
    Name: "Bru",
    category: "Grocery & Kitchen",
    Quantity: "250 gm",
    Price: 80,
    Picture: require("../assets/svg/bru.jpg"),
  },
  {
    id: 8,
    Name: "chanagapapu",
    category: "Grocery & Kitchen",
    Quantity: "1Kg",
    Price: 140,
    Picture: require("../assets/svg/chanagapapu.jpg"),
  },
  {
    id: 9,
    Name: "freedom",
    category: "Grocery & Kitchen",
    Quantity: "1L",
    Price: 140,
    Picture: require("../assets/svg/freedom.jpg"),
  },
  {
    id: 10,
    Name: "gasalu",
    category: "Grocery & Kitchen",
    Quantity: "100gm",
    Price: 40,
    Picture: require("../assets/svg/gasalu.jpg"),
  },
  {
    id: 11,
    Name: "gold drop",
    category: "Grocery & Kitchen",
    Quantity: "1L",
    Price: 140,
    Picture: require("../assets/svg/golddrop.jpg"),
  },
  {
    id: 12,
    Name: "Horlicks",
    category: "Grocery & Kitchen",
    Quantity: "1 kg",
    Price: 280,
    Picture: require("../assets/svg/horlicks.jpg"),
  },
  {
    id: 13,
    Name: "Jeera",
    category: "Grocery & Kitchen",
    Quantity: "100gm",
    Price: 40,
    Picture: require("../assets/svg/jeera.jpg"),
  },
  {
    id: 14,
    Name: "Kandi Papu",
    category: "Grocery & Kitchen",
    Quantity: "1Kg",
    Price: 130,
    Picture: require("../assets/svg/kandipapu.jpg"),
  },
  {
    id: 15,
    Name: "swastikMirchi",
    category: "Grocery & Kitchen",
    Quantity: "1Kg",
    Price: 240,
    Picture: require("../assets/svg/swastikMirchi.jpg"),
  },
  {
    id: 16,
    Name: "5 Star",
    category: "Snacks",
    Quantity: "1",
    Price: 5,
    Picture: require("../assets/svg/5Star.jpg"),
  },
  {
    id: 17,
    Name: "Dairy Milk",
    category: "Snacks",
    Quantity: "1",
    Price: 5,
    Picture: require("../assets/svg/dairyMilk.jpg"),
  },
  {
    id: 18,
    Name: "Good Day",
    category: "Snacks",
    Quantity: "1",
    Price: 5,
    Picture: require("../assets/svg/goodDay.jpg"),
  },
  {
    id: 19,
    Name: "Hide n Seek",
    category: "Snacks",
    Quantity: "1",
    Price: 30,
    Picture: require("../assets/svg/HideSeek.jpg"),
  },
  {
    id: 20,
    Name: "Krack Jack",
    category: "Snacks",
    Quantity: "1",
    Price: 5,
    Picture: require("../assets/svg/krackjak.jpg"),
  },
  {
    id: 21,
    Name: "Kurkure",
    category: "Snacks",
    Quantity: "1",
    Price: 5,
    Picture: require("../assets/svg/kurkure.jpg"),
  },
  {
    id: 22,
    Name: "Lays (Blue)",
    category: "Snacks",
    Quantity: "1",
    Price: 5,
    Picture: require("../assets/svg/LaysB.jpg"),
  },
  {
    id: 23,
    Name: "Lays (Green)",
    category: "Snacks",
    Quantity: "1",
    Price: 5,
    Picture: require("../assets/svg/LaysG.jpg"),
  },
  {
    id: 24,
    Name: "Lays (Yellow)",
    category: "Snacks",
    Quantity: "1",
    Price: 5,
    Picture: require("../assets/svg/LaysY.jpg"),
  },
  {
    id: 25,
    Name: "Mixture",
    category: "Snacks",
    Quantity: "100 gm",
    Price: 20,
    Picture: require("../assets/svg/mixture.jpg"),
  },
  {
    id: 26,
    Name: "perk",
    category: "Snacks",
    Quantity: "1",
    Price: 5,
    Picture: require("../assets/svg/Perk.jpg"),
  },
  {
    id: 27,
    Name: "Mixture",
    category: "Snacks",
    Quantity: "100 gm",
    Price: 20,
    Picture: require("../assets/svg/mixture.jpg"),
  },
  {
    id: 28,
    Name: "Fair n Lovely",
    category: "Beauty & Personal Care",
    Quantity: "200 gm",
    Price: 56,
    Picture: require("../assets/svg/fairAndLovely.jpg"),
  },
  {
    id: 29,
    Name: "Ponds Sandal",
    category: "Beauty & Personal Care",
    Quantity: "200 gm",
    Price: 56,
    Picture: require("../assets/svg/ponds.jpg"),
  },
  {
    id: 30,
    Name: "Ponds Magic",
    category: "Beauty & Personal Care",
    Quantity: "200 gm",
    Price: 56,
    Picture: require("../assets/svg/pondsP.jpg"),
  },
  {
    id: 31,
    Name: "Vaseline",
    category: "Beauty & Personal Care",
    Quantity: "50 gm",
    Price: 45,
    Picture: require("../assets/svg/vaseline.jpg"),
  },
  {
    id: 32,
    Name: "Vaseline Lotion",
    category: "Beauty & Personal Care",
    Quantity: "200 gm",
    Price: 185,
    Picture: require("../assets/svg/vaselineLotion.jpg"),
  },
  {
    id: 33,
    Name: "Jaddu",
    category: "HouseHold Essentials",
    Quantity: "1",
    Price: 25,
    Picture: require("../assets/svg/jaddu.jpg"),
  },
  {
    id: 34,
    Name: "Chipiri",
    category: "HouseHold Essentials",
    Quantity: "1",
    Price: 25,
    Picture: require("../assets/svg/chipiri.jpg"),
  },
  {
    id: 35,
    Name: "Pheneoyl",
    category: "HouseHold Essentials",
    Quantity: "1",
    Price: 40,
    Picture: require("../assets/svg/pheneyol.jpg"),
  },
  {
    id: 36,
    Name: "Surf Excel",
    category: "HouseHold Essentials",
    Quantity: "1",
    Price: 285,
    Picture: require("../assets/svg/surfExcel.jpg"),
  },
  {
    id: 36,
    Name: "Surf Excel Soap",
    category: "HouseHold Essentials",
    Quantity: "1",
    Price: 30,
    Picture: require("../assets/svg/surfExcelSoap.jpg"),
  },
  {
    id: 37,
    Name: "Vim Bar",
    category: "HouseHold Essentials",
    Quantity: "1",
    Price: 20,
    Picture: require("../assets/svg/vimSoap.jpg"),
  },
  {
    id: 38,
    Name: "Vim Extra",
    category: "HouseHold Essentials",
    Quantity: "1",
    Price: 20,
    Picture: require("../assets/svg/vimExtra.jpg"),
  },
];
